### ISSUE TITLE
Manifest tagging

### ISSUE THREAD

**Issue by aptalca** [drone-plugins/drone-manifest#24]
Just trying to understand the manifest tagging. The docs seem to be missing some info.

It seems that the [manifest.tmpl](https://github.com/drone-plugins/drone-manifest/blob/master/docker/manifest.tmpl) this repo uses does not update the `latest` tag on docker hub when the repo is tagged.

It seems the tag `latest` is only updated during pushes to master, in which case there is no versioning, so the tags pushed are `latest` as well as the os-arch tags like `linux-amd64` and `linux-arm64`. But when the repo is tagged, then only the image tags with github tags are pushed. Was that the intended behavior or an oversight?

I added `latest` to the tags to the tags section in the manifest.tmpl so `latest` is updated when the repo is tagged. Is that expected to cause any issues?

Also, the docs mention `auto_tag` as an option to be used in `spec`. Any examples of how it should be done?

Here is my test repo manifest.tmpl for reference: https://github.com/aptalca/zap2xml/blob/master/manifest.tmpl

Thanks

**Comment by tboerger** [comment]
`latest` is intentinally not changed on tgas, for the plugins organization `latest` always matches the master branch. The `auto_tag` feature gets used on nearly all plugins within this organization in combination with the manifest template.
