### ISSUE TITLE
from-args does not work because it is missing from-args

### ISSUE THREAD

**Issue by deitch** [drone-plugins/drone-manifest#25]
Doing `from-args`, i.e. without a manifest template spec, just doesn't work. Running it gives:

```
Incorrect Usage.

NAME:
   /bin/manifest-tool push - push a manifest list entry to a registry with provided image details

USAGE:
   /bin/manifest-tool push command [command options] [arguments...]

COMMANDS:
   from-spec	push a manifest list to a registry via a YAML spec
   from-args	push a manifest list to a registry via CLI arguments
   help, h	Shows a list of commands or help for one command

OPTIONS:
   --help, -h	show help

time="2019-06-06T09:45:53Z" level=fatal msg="flag provided but not defined: -platforms"
2019/06/06 09:45:53 exit status 1
```

Looking at the code, it appears that it never passes `from-args` to the `/bin/manifest-tool` command. It _does_ pass `from-spec` when needed, but not `from-args`. It adds `from-spec` [here](https://github.com/drone-plugins/drone-manifest/blob/master/plugin.go#L118), but the place to do the same for `from-args` [here](https://github.com/drone-plugins/drone-manifest/blob/master/plugin.go#L125) has nothing. 

Should be a simple fix.

**Comment by tboerger** [comment]
You seem to be right, could you create a PR to fix that? Thanks.

**Comment by deitch** [comment]
Sure.

**Comment by dirkcjelli** [comment]
I'd really love to see this merged :)

**Comment by tboerger** [comment]
Thanks for the headsup, I simply forgot about this PR/issue ;)

**Comment by dessalines** [comment]
This doesn't seem to be documented.
