### ISSUE TITLE
Inline spec

### ISSUE THREAD

**Issue by sh0rez** [drone-plugins/drone-manifest#27]
It would be nice if the `spec` would take a literal string containing what's usually in the file. This would allow for generating these, e.g. using `jsonnet`.

**Comment by tboerger** [comment]
We are just wrapping https://github.com/estesp/manifest-tool, so if this doesn't provide the required options it won't get into this plugin.

**Comment by sh0rez** [comment]
No need to change manifest-tool. 

Currently, we allow to pass the filename for manifest-tool to use to the `spec` parameter.

However, when using something like `jsonnet` to generate the `drone.yml`, out would be awesome to pass the contents of the file manifest-tool is going use directly inside of `drone.yml`. This would require this plugin to write those contents to a temporary file before invoking manifest-tool though.

**Comment by tboerger** [comment]
You can easily generate the manifest template in a previous step and just define this path to the generated spec template via

```
settings:
  spec: path/to/generated/manifest.tmpl
```

No need to change anything on this plugin.

**Comment by sh0rez** [comment]
This does not apply if I use https://docs.drone.io/extend/config/jsonnet/ to dynamically generate the config at pipeline run-time.

The sole purpose of https://docs.drone.io/extend/config/jsonnet/ is not having to check-in generated files into git. To make this promise come true, it is required that I can pass such a config like the `spec` from the `drone.yml` as well.

**Comment by tboerger** [comment]
I don't know what you are talking about. Jsonnet is simply generating a .drone.yml which had been specified via jsonnet. You can pass any settings you want, including the spec attribute.

**Comment by sh0rez** [comment]
From https://docs.drone.io/extend/config/jsonnet:
> The jsonnet extension **fetches** the configuration file from **your repository**. If the configuration file has a .jsonnet file extension it is dynamically converted to yaml. This extension is useful when you want to use jsonnet as the configuration language, but you **do not want to commit the generated yaml file to version control**.

This means, that it allows me to use jsonnet, **without pushing the generated yaml to GitHub**. I will **only** add the `.jsonnet` to GitHub and drone will generate the yaml on the fly.

But you propose I should push the **generated** `manifest.tmpl` to GitHub, with is kind of contradictory to what the jsonnet plugin is trying to achieve.

So, I would like to optionally allow passing the contents of `manifest.tmpl` directly from `drone.jsonnet` instead of the filename. This plugin would then go and render the template from it's config and not from a file.

**Comment by tboerger** [comment]
I have never said that you got to push a generated manifest.tmpl to github, you can define a step that generates the manifest.tmpl within a previous step which can be used by the plugin:

```
[
  {
    kind: 'pipeline',
    name: 'default',
    platform: {
      os: 'linux',
      arch: 'amd64',
    },
    steps: [
      {
        name: 'generate',
        image: 'ubuntu',
        commands: [
        	'echo "image: foo/bar:latest" >> manifest.tmpl',
        	'echo "manifests:" >> manifest.tmpl',
        	'echo "- image: foo/bar:linux-amd64" >> manifest.tmpl',
        	'echo "  platform:" >> manifest.tmpl',
        	'echo "    architecture: amd64" >> manifest.tmpl',
        	'echo "    os: linux" >> manifest.tmpl',
        ],
      },
      {
        name: 'manifest',
        image: 'plugins/manifest',
        settings: {
          spec: 'manifest.tmpl',
        },
      },
    ],
  }
]
```
